In [4]:
import numpy as np

# EP 5: Array

## EP 5.0: Even entries first

In [5]:
a = list(range(100))
%time b = a[1::2]+a[::2]

CPU times: user 8 µs, sys: 1 µs, total: 9 µs
Wall time: 17.2 µs


In [41]:
a = list(range(100))
%time
for i in range(len(a)//2):
    a[i], a[2*i+1] = a[2*i+1], a[i]


CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 4.05 µs


## EP 5.1: Dutch national flag problem

## EP 5.5 Delete dupicated numbers from a sorted array 

In [15]:
a = [2,3,5,5,7,77,11,17,13, 13 ,13, 13, 55,55, 0]
N = len(a)
i = j = 1
while j < N:
    while a[j] == a[j-1]:
        if j < N-1:
            j += 1
        else:
            break
    a[i] = a[j]
    i += 1
    j += 1
res = a[:i]
res        

[2, 3, 5, 7, 77, 11, 17, 13, 55, 0]

## EP 5.14: Compute random permutation

## EP 5.18: Compute spiral orderin of 2d array

In [77]:
dim_x = 4
a = np.reshape(range(dim_x**2), (dim_x, dim_x))
r_max, c_max = a.shape[0], a.shape[1]
r_min, c_min = (0, 0)
res = []
while ((r_min < r_max) & (c_min < c_max)):
    for j in range(c_min, c_max):
        res.append(a[r_min, j])
    r_min += 1
    for i in range(r_min, r_max):
        res.append(a[i, c_max-1])
    c_max -= 1
    for j in range(c_max-1, c_min-1, -1):
        res.append(a[r_max-1, j])
    r_max -= 1
    for i in range(r_max-1, r_min-1, -1):
        res.append(a[i, c_min])
    c_min += 1
print(f'Orig:\n {a} \n Spiral order: \n {res}')

Orig:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 
 Spiral order: 
 [0, 1, 2, 3, 7, 11, 15, 14, 13, 12, 8, 4, 5, 6, 10, 9]


## EP 5.19: Rotate 2d array

## EP 5.20: Compute Nth row in Pascal's triangle

# EP 6: String

## EP 6.0: Test panlindromicity

In [14]:
# s = 'adb3kdda3k3008mdaf'
# s[~2], s[~1], s[~0], s[-3], s[-2], s[-1]
s = 'annaaanna'
def is_pan(s):
    return all(s[i] == s[-(i+1)] for i in range(len(s)//2))
is_pan(s)

True

In [24]:
list(reversed('ddd3'))

['3', 'd', 'd', 'd']

In [28]:
s = 'ddd9ddd'
def is_pan1(s):
    return s == ''.join(reversed(s))
is_pan1(s)

True

## EP 6.1: atoi, itoa

In [23]:
def atoi(s):
    start = 1 if s[0]=='-' else 0
    res = int(s[start])
    for i in range(1+start, len(s)):
        res = 10*res + int(s[i])
    return res * (-1)**start
s = '992343242'
atoi(s)


992343242

In [ ]:
def itoa(i):
    start = 1 if i < 0 else 0
    s = [i//10**j for j in range(len(i))]

## EP 6.4: Column name -> Decimal

In [5]:
s = 'AA'
res = 0
for c in s:
    res += ord(c) - ord('A') + 1
res

2

In [35]:
s = 'ZZ'
from functools import reduce
def col_to_num(s):
    return reduce(lambda running_sum, y: running_sum * 26 + ord(y) - ord('A') + 1, s, 0)
col_to_num(s)

702

EP 6.6: Reveser words in a sentence

In [47]:
Counter(a)

Counter({'d': 3, 'a': 2, 'c': 1})

In [52]:
from collections import Counter
a = 'dddaac'
# [k for k, v in Counter(a) if v == 1][0]
[(k, v) for k, v in Counter(a).items()]

[('d', 3), ('a', 2), ('c', 1)]

EP 6.0: Test panlindromicity

In [60]:
[""] == True

False

EP 6.0: Test panlindromicity

# EP 7: Linked list 

## EP 7.0: Build linked list, search, insert, delete

In [11]:
class ListNode:
    def __init__(self, data=0, next=None):
        self.data = data
        self.next = next

def insert_node(curr_node, new_node):
    ''' insert after curr_node'''
    if curr_node is not None:
        new_node.next = curr_node.next
        curr_node.next = new_node
    return new_node

def print_linked_list(head):
    while head is not None:
        i, head = head.data, head.next
        print(f'{i}')

def build_linked_list(a):
    head = tail = ListNode(data=a[0])
    if len(a) == 1:
        return head
    for i in a[1:]:
        tail = insert_node(tail, ListNode(i))
    return head

def search_node(head, data):
    while head is not None:
        if head.data == data:
            return head
        head = head.next

def delete_node(node):
    # delete the node after
    pass

a = [3, 4, 5, 23,-33]
head = build_linked_list(a)
print_linked_list(head)


3
4
5
23
-33


## EP7.1 Merge two sorted lists

In [14]:
def merge_sorted_lists(head1, head2):
    curr1, curr2 = head1, head2
    head = curr = ListNode()
    while curr1 and curr2:
        if curr1.data < curr2.data:
            curr.next, curr1 = curr1, curr1.next
        else:
            curr.next, curr2 = curr2, curr2.next
        curr = curr.next
    curr.next = curr2 if not curr1 else curr1
    return head.next
        

a = [-33, 3, 4, 5, 23]
head1 = build_linked_list(a)
b = [-2, 0, 1, 4, 66]
head2 = build_linked_list(b)
head_merge=merge_sorted_lists(head1, head2)
print_linked_list(head_merge)

-33
-2
0
1
3
4
4
5
23
66


In [15]:
head1 or head1

# EP 8: Stack
## EP 8.0: Reverse linked list

## EP 8.3: Test well-formedness of parenthesis/braces/brackets

## EP 8.5: Find building with sunset view

In [59]:
str(3)

'3'

## EP 8.8 Implement queue using stack

In [32]:
class queue:
    def __init__(self):
        self.stack1, self.stack2 = [], []
        
    def enqueue(self, i):
        self.stack1.append(i)
        
    def dequeue(self):
        while len(self.stack1):
            self.stack2.append(self.stack1.pop())
        if len(self.stack2):
            return self.stack2.pop()
        else:
            print('Empty queue')

a = [-33, 3, 4, 5, 23]
q = queue()
[q.enqueue(i) for i in a]
q.dequeue()


-33