In [45]:
import numpy as np

# EP 5: Array

EP 5.0: Even entries first

In [38]:
a = list(range(100))
%time b = a[1::2]+a[::2]

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 7.15 µs


In [41]:
a = list(range(100))
%time
for i in range(len(a)//2):
    a[i], a[2*i+1] = a[2*i+1], a[i]


CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 4.05 µs


EP 5.1: Dutch national flag problem

EP 5.5 Delete dupicated numbers from a sorted array 

In [4]:
a = [2,3,5,5,7,77,11,17,13]
N = len(a)
for i in range(N):
    if a[i] == a[i+1]:
        for j in range(N):
            
        

SyntaxError: invalid syntax (<ipython-input-4-03d43c05850f>, line 4)

EP 5.14: Compute random permutation

EP 5.18: Compute spiral orderin of 2d array

In [77]:
dim_x = 4
a = np.reshape(range(dim_x**2), (dim_x, dim_x))
r_max, c_max = a.shape[0], a.shape[1]
r_min, c_min = (0, 0)
res = []
while ((r_min < r_max) & (c_min < c_max)):
    for j in range(c_min, c_max):
        res.append(a[r_min, j])
    r_min += 1
    for i in range(r_min, r_max):
        res.append(a[i, c_max-1])
    c_max -= 1
    for j in range(c_max-1, c_min-1, -1):
        res.append(a[r_max-1, j])
    r_max -= 1
    for i in range(r_max-1, r_min-1, -1):
        res.append(a[i, c_min])
    c_min += 1
print(f'Orig:\n {a} \n Spiral order: \n {res}')

Orig:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 
 Spiral order: 
 [0, 1, 2, 3, 7, 11, 15, 14, 13, 12, 8, 4, 5, 6, 10, 9]


TypeError: unsupported operand type(s) for -: 'tuple' and 'int'

EP 5.19: Rotate 2d array

EP 5.20: Compute Nth row in Pascal's triangle

# EP 6: String

EP 6.0: Test panlindromicity

In [4]:
s = 'adb3kdda3k3008mdaf'
s[~2]
display(21//4, 21%4)

5

1

EP 6.1: atoi, itoa

In [23]:
def atoi(s):
    start = 1 if s[0]=='-' else 0
    res = int(s[start])
    for i in range(1+start, len(s)):
        res = 10*res + int(s[i])
    return res * (-1)**start
s = '992343242'
atoi(s)


992343242

In [ ]:
def itoa(i):
    start = 1 if i < 0 else 0
    s = [i//10**j for j in range(len(i))]

EP 6.6: Reveser words in a sentence

EP 6.0: Test panlindromicity

EP 6.0: Test panlindromicity

# EP 7: Linked list 

EP 7.0: Build linked list, search, insert, delete

In [43]:
class ListNode:
    def __init__(self, data=0, next_node=None):
        self.data = data
        self.next_node = next_node

def insert_node(curr_node, new_node):
    ''' insert after curr_node'''
    if curr_node is not None:
        new_node.next_node = curr_node.next_node
        curr_node.next_node = new_node
    return new_node

def print_linked_list(head):
    while head is not None:
        i, head = head.data, head.next_node
        print(f'{i}')

def build_linked_list(a):
    head = tail = ListNode(data=a[0])
    if len(a) == 1:
        return head
    for i in a[1:]:
        tail = insert_node(tail, ListNode(i))
    return head

def search_node(head, data):
    while head is not None:
        if head.data == data:
            return head
        head = head.next

def delete_node(node):
    # delete the node after

a = [3, 4, 5, 23,-33]
head = build_linked_list(a)
print_linked_list(head)


3
4
5
23
-33


In [59]:
str(3)

'3'